server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://8.129.112.196:3306/luntan?serverTimezone=GMT%2B8
    username: root
    password: 687211

mybatis:
  mapper-locations: classpath:com/zzc/mapper/*.xml
